Update README.md
Azure/aistudio-copilot-sample pull request #108
Opened 2024-03-25 21:57 UTC by jenfoxbot

Modified flow (get credentials before running sample) and added context/clarity

2024-03-28 16:47 UTC, paulshealy1 commented on README.md
> +This repository contains a copilot getting sample that can be used with the the [Azure AI Studio preview](https://aka.ms/azureai/docs).
This looks like a typo - either "copilot sample" or "copilot getting started sample".

2024-03-28 20:57 UTC, paulshealy1 requested changes

2024-03-28 20:57 UTC, paulshealy1 commented on README.md
> +:warning: If you are using Python 3.12, there is a package dependency issue we are working to resolve. Check your python version, and if the version is 3.12, use the commented 3.12 alternative for cr
3.12 is supported, and we can take out the parts that are 3.12-specific.

2024-03-30 17:09 UTC, paulshealy1 approved these changes

2024-04-01 16:53 UTC, merged

2024-04-22 10:44 UTC, Moazzem-Hossain-pixel reviewed
Thank you for contributing.

2024-04-22 10:47 UTC, Moazzem-Hossain-pixel reviewed
Thanks